services:
  - type: web
    name: theme-sections-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SHOPIFY_API_KEY
        value: cf5df4d826a3faea551a29eec40ad090
      - key: SHOPIFY_API_SECRET
        value: a750fba3926ae2137fdac14dff34631c
      - key: SCOPES
        value: write_products,write_customers,write_draft_orders,write_themes,write_content
      - key: PORT
        value: 3000 