services:
  - type: web
    name: theme-sections-app
    env: node
    plan: free
    branch: main
    buildCommand: npm ci --omit=dev
    startCommand: node simple-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        value: cf5df4d826a3faea551a29eec40ad090
      - key: SHOPIFY_API_SECRET
        value: a750fba3926ae2137fdac14dff34631c
      - key: SCOPES
        value: read_themes,write_themes,read_files,write_files,read_content,write_content,read_products,write_products,read_script_tags,write_script_tags
      - key: PORT
        value: 3000
      - key: HOST
        value: https://theme-sections-app-chjk.onrender.com
      - key: OKAYSCALE_DEMO_TOKEN
        sync: false
